"""Write a runnable Telegram bot project from a RepoAnalysis."""

import json
import os
import re
from typing import Optional

from . import llm
from .config import GENERATION_MAX_TOKENS
from .models import RepoAnalysis, RepoDigest

# --------------------------------------------------------------------------
# Static supporting files (rendered with a simple {{PLACEHOLDER}} scheme so
# the Python in the templates does not fight str.format's braces).
# --------------------------------------------------------------------------

_REQUIREMENTS = "python-telegram-bot>=21.0\n"

_ENV = """# Telegram bot token from @BotFather (required).
BOT_TOKEN=

# Path to a local checkout of the source repository this bot wraps.
# Required only when the bot shells out to the repo's CLI.
REPO_DIR={{REPO_DIR}}

# Optional: comma-separated Telegram user IDs allowed to use the bot.
# Leave empty to allow everyone (not recommended for anything sensitive).
ALLOWED_USER_IDS=
"""

_GITIGNORE = "__pycache__/\n*.pyc\n.env\n"

_DOCKERFILE = """FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "bot.py"]
"""

_README = """# {{NAME}} — Telegram bot

Generated by **telegram-bot-builder** from [`{{URL}}`]({{URL}}).

## What it does

{{PURPOSE}}

Integration strategy: **{{STRATEGY}}** — {{RATIONALE}}

## Commands

{{COMMANDS}}

## Setup

1. Create a bot with [@BotFather](https://t.me/BotFather) and copy its token.
2. `cp .env.example .env` and fill in `BOT_TOKEN`.{{REPO_STEP}}
3. `pip install -r requirements.txt`
4. `python bot.py`

{{NOTES}}

---

_This bot was scaffolded automatically. Review the code before deploying it, and
only run it against systems and accounts you are authorized to operate._
"""

# Heuristic (offline) bot: wraps the repo's CLI behind a /run command.
_HEURISTIC_BOT = r'''#!/usr/bin/env python3
"""Telegram bot for {{NAME}} (generated by telegram-bot-builder, offline mode).

This scaffold wraps the source project's command-line entry point. Re-generate
with API access for a logic-aware bot with per-capability commands.
"""

import asyncio
import os
import shlex

from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

BOT_TOKEN = os.environ["BOT_TOKEN"]
REPO_DIR = os.environ.get("REPO_DIR", ".")
RUN_COMMAND = {{RUN_COMMAND!r}}
ALLOWED = {int(x) for x in os.environ.get("ALLOWED_USER_IDS", "").replace(",", " ").split() if x}

HELP = (
    "*{{NAME}} bot*\n"
    "{{PURPOSE}}\n\n"
    "/run `<args>` — run the tool with the given arguments\n"
    "/help — show this message"
)


def _authorized(update: Update) -> bool:
    return not ALLOWED or (update.effective_user and update.effective_user.id in ALLOWED)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(HELP, parse_mode="Markdown")


async def run(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not _authorized(update):
        await update.message.reply_text("Not authorized.")
        return
    if not RUN_COMMAND:
        await update.message.reply_text("No run command was detected for this project.")
        return
    args = context.args or []
    argv = shlex.split(RUN_COMMAND) + args
    try:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            cwd=REPO_DIR,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=60)
    except asyncio.TimeoutError:
        await update.message.reply_text("Command timed out after 60s.")
        return
    except FileNotFoundError:
        await update.message.reply_text(
            "Could not launch the tool. Check REPO_DIR and that its runtime is installed."
        )
        return
    text = out.decode("utf-8", errors="replace").strip() or "(no output)"
    for i in range(0, len(text), 3800):
        await update.message.reply_text("```\n" + text[i:i + 3800] + "\n```", parse_mode="Markdown")


def main() -> None:
    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler(["start", "help"], start))
    app.add_handler(CommandHandler("run", run))
    app.run_polling()


if __name__ == "__main__":
    main()
'''

# --------------------------------------------------------------------------
# LLM generation
# --------------------------------------------------------------------------

_GEN_SYSTEM = """You are an expert Python engineer. Write a complete, runnable \
Telegram bot in a single file (`bot.py`) that reproduces the behavior of a given \
source repository, following the provided analysis.

Requirements:
- Use python-telegram-bot v21+ (async: `Application`, `CommandHandler`, `ContextTypes`).
- Read the bot token from the BOT_TOKEN environment variable.
- Implement `/start` and `/help`, plus one handler per command in the analysis.
- Honor the analysis's integration strategy:
  * cli_wrap    -> invoke the repo's CLI via asyncio subprocess (cwd from the REPO_DIR
                   env var, default "."), with a timeout; never build shell strings from
                   user input — pass argv lists.
  * reimplement -> port the repo's core logic directly into bot.py (pure functions).
  * api_wrap    -> import and call the repo's library functions.
- Validate user input, handle errors, and split long replies under Telegram's 4096-char limit.
- Support an optional ALLOWED_USER_IDS env allow-list (comma/space separated).

Hard safety rule: do NOT write any code that collects a user's passwords, cookies, \
browser data, private keys, or other secrets and sends them to the chat or any remote \
endpoint. If a requested command would do that, implement it as a stub that replies that \
the action is disabled for safety, and add a comment explaining why.

Output ONLY the contents of bot.py — no prose, no markdown code fences."""


def _gen_prompt(analysis: RepoAnalysis, digest: RepoDigest) -> str:
    parts = [
        "ANALYSIS:",
        json.dumps(analysis.to_dict(), indent=2),
        "",
        f"Repository: {digest.name} ({digest.url})",
        f"Primary language: {digest.primary_language}",
        f"Entry points: {', '.join(digest.entry_points) or 'none detected'}",
    ]
    if analysis.integration_strategy == "reimplement" and digest.key_files:
        parts += ["", "SOURCE (for reimplementation):"]
        for path, content in list(digest.key_files.items())[:4]:
            parts += [f"--- {path} ---", content]
    if digest.readme:
        parts += ["", "README (excerpt):", digest.readme[:4000]]
    return "\n".join(parts)


_FENCE_RE = re.compile(r"^```[a-zA-Z]*\n(.*)\n```$", re.DOTALL)


def _strip_fences(text: str) -> str:
    text = text.strip()
    m = _FENCE_RE.match(text)
    return m.group(1) if m else text


def _generate_bot_code_llm(analysis: RepoAnalysis, digest: RepoDigest,
                           model: Optional[str]) -> str:
    raw = llm.generate_text(_GEN_SYSTEM, _gen_prompt(analysis, digest), model,
                            GENERATION_MAX_TOKENS)
    return _strip_fences(raw)


def _render_heuristic_bot(analysis: RepoAnalysis, digest: RepoDigest) -> str:
    return (
        _HEURISTIC_BOT
        .replace("{{NAME}}", digest.name)
        .replace("{{PURPOSE}}", analysis.purpose.replace('"', "'"))
        .replace("{{RUN_COMMAND!r}}", repr(analysis.run_command or ""))
    )


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------

def _render_readme(analysis: RepoAnalysis, digest: RepoDigest) -> str:
    if analysis.commands:
        cmd_lines = "\n".join(
            f"- `{c.usage}` — {c.description}" for c in analysis.commands
        )
    else:
        cmd_lines = "- `/run <args>` — run the wrapped tool"
    repo_step = ""
    if analysis.integration_strategy == "cli_wrap":
        repo_step = (
            "\n   Clone the source repo somewhere and set `REPO_DIR` in `.env` to its path."
        )
    return (
        _README
        .replace("{{NAME}}", digest.name)
        .replace("{{URL}}", digest.url)
        .replace("{{PURPOSE}}", analysis.purpose)
        .replace("{{STRATEGY}}", analysis.integration_strategy)
        .replace("{{RATIONALE}}", analysis.strategy_rationale or "n/a")
        .replace("{{COMMANDS}}", cmd_lines)
        .replace("{{NOTES}}", analysis.setup_notes or "")
        .replace("{{REPO_STEP}}", repo_step)
    )


def generate(analysis: RepoAnalysis, digest: RepoDigest, out_dir: str,
             use_llm: bool, model: Optional[str] = None) -> str:
    """Write the bot project to `out_dir`; return the path to bot.py."""
    os.makedirs(out_dir, exist_ok=True)

    if use_llm:
        bot_code = _generate_bot_code_llm(analysis, digest, model)
    else:
        bot_code = _render_heuristic_bot(analysis, digest)

    default_repo_dir = "./source-repo"
    files = {
        "bot.py": bot_code,
        "requirements.txt": _REQUIREMENTS,
        ".env.example": _ENV.replace("{{REPO_DIR}}", default_repo_dir),
        ".gitignore": _GITIGNORE,
        "Dockerfile": _DOCKERFILE,
        "README.md": _render_readme(analysis, digest),
    }
    for name, content in files.items():
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
            fh.write(content if content.endswith("\n") else content + "\n")

    return os.path.join(out_dir, "bot.py")
